### ISSUE TITLE
UnboundLocalError: local variable 'individual_score_dict' referenced before assignment

### ISSUE THREAD

**Issue by dakl** [moonso/vcf_parser#2]
Hi, 

I installed vcf_parser with `pip install`. 

However, when testing it with `vcf_parser my.vcf --split`, I get this error: 

```
##fileformat=VCFv4.1
##FORMAT=<ID=AO,Number=A,Type=Integer,Description="Alternate allele observation count">
##FORMAT=<ID=DP,Number=1,Type=Integer,Description="Read Depth">
<snip>
##SnpEffCmd="SnpEff  -csvStats -stats /mnt/hds/proj/cust001/clinseq/BREASTv6/L12982/datareports/DataReport_L12982T/L12982N_panel_v1.freebayes.sorted.leftAligned.annotated.stats.txt -lof -hgvs GRCh37.75 /mnt/hds/proj/cust001/clinseq/BREASTv6/L12982/datareports/DataReport_L12982T/L12982N_panel_v1.freebayes.sorted.leftAligned.vcf "
#CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO	FORMAT	L12982N_panel_v1
Traceback (most recent call last):
  File "/Users/dankle/.pyenv/versions/2.7.8/bin/vcf_parser", line 108, in <module>
    vcf_parser()
  File "/Users/dankle/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 610, in __call__
    return self.main(*args, **kwargs)
  File "/Users/dankle/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 590, in main
    rv = self.invoke(ctx)
  File "/Users/dankle/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 782, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/dankle/.pyenv/versions/2.7.8/lib/python2.7/site-packages/click/core.py", line 416, in invoke
    return callback(*args, **kwargs)
  File "/Users/dankle/.pyenv/versions/2.7.8/bin/vcf_parser", line 99, in vcf_parser
    for variant in my_parser:
  File "/Users/dankle/.pyenv/versions/2.7.8/lib/python2.7/site-packages/vcf_parser/parser.py", line 317, in __iter__
    first_variant = self.format_variant(self.next_line)
  File "/Users/dankle/.pyenv/versions/2.7.8/lib/python2.7/site-packages/vcf_parser/parser.py", line 784, in format_variant
    variant['individual_scores'] = individual_score_dict
UnboundLocalError: local variable 'individual_score_dict' referenced before assignment
```

I.e. it prints the header, but then breaks when working on the variants. When I use it in a script, it breaks with the same error:

```
$ python vcf-parser-test.py 
Traceback (most recent call last):
  File "vcf-merge-records.py", line 5, in <module>
    for variant in my_parser:
  File "/Users/dankle/.pyenv/versions/2.7.8/lib/python2.7/site-packages/vcf_parser/parser.py", line 317, in __iter__
    first_variant = self.format_variant(self.next_line)
  File "/Users/dankle/.pyenv/versions/2.7.8/lib/python2.7/site-packages/vcf_parser/parser.py", line 784, in format_variant
    variant['individual_scores'] = individual_score_dict
UnboundLocalError: local variable 'individual_score_dict' referenced before assignment
``` 

Contents of the script, as per example: 

```
$ cat vcf-parser-test.py 
#!/usr/bin/env python

from vcf_parser import VCFParser
my_parser = VCFParser(infile='db.vcf')
for variant in my_parser:
    print(variant)

```

```
$ python -V
Python 2.7.8
```

Thanks

**Comment by moonso** [comment]
Hello! This should be fixed now. 
Updated to version 1.1.4 so please update and try again.

**Comment by dakl** [comment]
Works like a charm, thanks!

**Comment by moonso** [comment]
:)
